language: python
python:
   - "2.7"
install:
   - sudo apt-get install --assume-yes libhdf5-serial-dev libboost-dev libboost-python-dev
   - sudo apt-get install -y libjpeg-dev libtiff4-dev libpng12-dev libhdf5-serial-dev cmake
   - sudo sh .travis_scripts/install_vigra.sh $VIRTUAL_ENV
   - mkdir build && cd build
   - cmake -DCMAKE_BUILD_TYPE=Release ..
   - make
script:
   - make test
